language: python
python:
  - "2.7"
cache:
  - apt
  - pip
env:
  - PYTHONPATH=/usr/share/python-support/root/:/usr/lib/x86_64-linux-gnu/
addons:
apt:
  packages:
    - root-system
before_install:
  - "travis_retry pip install --upgrade pip"

# command to install dependencies
install:
  - "travis_retry pip install -r requirements.txt"
# command to run tests
script:
  - "pip list"
  - "coverage run -m unittest discover hepdata_converter/testsuite 'test_*'"

after_success:
  - coveralls

sudo: false
