language: python
python:
  - "2.7"

sudo: required

cache:
  - docker

services:
  - docker

# docker must be in install to override defalut pip install -r requirements.txt
install:
  - echo 'running docker'
script:
  - "docker run -v `pwd`:/tmp/hepdata-converter hepdata/hepdata-converter /bin/bash -c \"cd  /tmp/hepdata-converter && coverage run -m unittest discover hepdata_converter/testsuite 'test_*'\""

after_success:
  - coveralls
