language: python
python:
  - "2.7"
cache:
  - apt
  - pip
addons:
apt:
before_install:
  - "travis_retry pip install --upgrade pip"

# command to install dependencies
install:
  - "travis_retry pip install -r requirements.txt"
# command to run tests
script:
  - "pip list"
  - "python -m unittest discover hepdata_converter/testsuite 'test_*'"

after_success:
  - coveralls

sudo: false