language: python
python:
  - "2.7"

sudo: required

cache:
  - docker

services:
  - docker

# docker must be in install to override defalut pip install -r requirements.txt
install:
  - sudo pip install --upgrade pip
script:
  - export CURRENT_PATH=`pwd`
  - "docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter /bin/bash -c \"cd  $CURRENT_PATH && coverage run -m unittest discover hepdata_converter/testsuite 'test_*'\""
  # check installation script
  - "docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter /bin/bash -c \"cd  $CURRENT_PATH && python setup.py install && hepdata-converter -v\""
after_success:
  - coveralls
