language: python
python:
  - "2.7"

sudo: required

services:
  - docker
cache:
  - apt
  - pip

env:
  - CC=gcc-4.8
    CXX=g++-4.8
    ROOTSYS=/usr/local/lib/root
    LD_LIBRARY_PATH=/usr/lib/python2.7/dist-packages/:/usr/local/lib:/usr/local/lib/python2.7/site-packages/yoda:/usr/share/python-support/root/:$LD_LIBRARY_PATH
    PYTHONPATH=/usr/lib/python2.7/dist-packages/:/usr/local/lib:/usr/local/lib/python2.7/site-packages:/usr/share/python-support/root/:$PYTHONPATH
before_install:
  # do things required to be inside container
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
  # update apt
  - sudo apt-get update
  # install all dependencies (YODA)
  - "sudo apt-get install git root-system-bin libroot-bindings-python5.34 dpkg-dev make g++-4.8 gcc-4.8 binutils libpng12-dev libx11-dev libxpm-dev libxft-dev libxext-dev python-dev libboost1.54-all-dev"
  # print compiler versions
  - "$CC -v"
  - "$CXX -v"
  # download and compile yoda with python bindings (no package for ubuntu 12.04 is available)
  - "wget http://www.hepforge.org/archive/yoda/YODA-1.4.0.tar.gz && tar -xzf YODA-1.4.0.tar.gz && cd YODA-1.4.0 && ./configure && make -j4 && sudo make install && cd .."
  - "travis_retry pip install --upgrade pip"

# command to install dependencies
install:
  - "travis_retry pip install -r requirements.txt"
# command to run tests
script:
  # list installed python packages for debug and reference
  - "pip list"
  - "coverage run -m unittest discover hepdata_converter/testsuite 'test_*'"

after_success:
  - coveralls
